# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Exploratory Missions
email: atti.balazs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A personal website where I share my ideas and collect useful resources.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://attibalazs.github.com" # the base hostname & protocol for your site
twitter_username: attibalazs
github_username:  attibalazs

# Build settings
markdown: kramdown
