# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Software Ranch
email: 
description: > # this means to ignore newlines until "baseurl:"
  A website where we share our thoughts about technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://softwareranch.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  softwareranch

# Build settings
markdown: kramdown #for details http://kramdown.gettalong.org/syntax.html
highlighter: rouge #details at https://github.com/jneen/rouge , https://sacha.me/articles/jekyll-rouge/ and http://www.rubydoc.info/gems/rouge/frames
include: ["_pages"] #see http://damonbauer.me/organizing-jekyll-pages/ for more details
permalink: /:title/ #pattern of keeping dates out of URLs; This will make your site’s URLs succinct and easy to read